### ISSUE TITLE
ListType resolve value ?incorrect? in custom resolver

### ISSUE THREAD

**Issue by akomm** [Youshido/GraphQL#119]
I'm not entirely sure if I got something wrong or it is a bug. ~I actually used _ListType__ in non-mutating queries and it was kind of obvious how it resolves.~ Has nothing to do with mutations. Just the value passed to custom resolve function seem weird.

I have something like that:
```php
// mutation field
class CreateReviewField extends AbstractContainerAwareField
{
    public function build(FieldConfig $config)
    {
        $config->addArguments([/* ... */]);
    }

    public function getType()
    {
        return new MutationResultType(new ReviewType());
    }
    
    public function resolve($value, array $args, ResolveInfo $info)
    {
        // at some point
        return [
            'errors' => ['a', 'b']
        ];
    }
}
// field type returned
class MutationResultType extends AbstractObjectType
{
    /**
     * @var TypeInterface
     */
    private $resultType;

    public function __construct(TypeInterface $resultType)
    {
        parent::__construct([
            'name'       => $resultType->getName() . 'MutationResult',
            'interfaces' => $this->getInterfaces()
        ]);

        $this->resultType = $resultType;
    }

    public function build($config)
    {
        $config->addFields([
            'result' => [
                'type' => $this->resultType
            ],
            'errors' => [
                'type'    => new ListType(new StringType()),
                'resolve' => function($value, $args, ResolveInfo $info) {
                    // expected: $value is ['a', 'b']
                    // actual: $value is ['errors' => ['a', 'b']]
                }
            ]
        ]);
    }
}
```

This behaviour contradicts with how I understood & successfully used resolvers so far.

__note__ when I let the default resolver work everything is fine.

**Comment by viniychuk** [comment]
@akomm You've been close, but a little bit misunderstood the idea. Resolve function takes a higher level value as an argument. 
So, let's say you have an `Article { id: ID, title(withAuthor: Bool): String, Author: string }`. 
You `Article` field resolver returns an object – Article, that has getTitle, getId and all other methods.
Now, inside the Article build function when you were adding a `title` field you also specified a custom resolver for it, to be able to process the argument `withAuthor`.
So that resolver (analogy to yours) needs access to the whole Article object to be able to do `return $value->getTitle() . (!empty($args['withAuthor']) ? ' author:' . $value->getAuthor() : '')`.
Sorry for my pseudocode I was just trying to give an example.

**Comment by akomm** [comment]
Thanks. That makes sense in your example. But what about an custom field? It has to be aware in which context it is used, when it access a higher level value. 

```php
class PersonInitials extends AbstractField
{
    public function getType()
    {
        return new StringType();
    }
    
    public function resolve($value, array $args, ResolveInfo $info)
    {
        if (!($value instanceof PersonInterface)) {
            return null;
        }
        return sprintf(
            "%s.%s.", 
            mb_substr($value->getForename(), 0, 1, 'utf8'),
            mb_substr($value->getSurname(), 0, 1, 'utf8')
        );
    }
}
```
```gql
query {
  books {
    author
  }
}
```

Now I would expect the higher order Field to resolve author from book and the field resolve to resolve the value (PersonInterface). 

I'v noticed that this idea has a flaw. I actually should have done this:

```gql
query {
  books {
    authorInitials
  }
}
```

At this moment, the higher order field can not resolve authorInitials, because it does not exist. on the value. And so the PersonInitials Field can not get an author value/object to resolve. 

So in theoretical the awareness question I made is correct, but practically I can not imagine a case where it would really work. The moment I create something that is - let's say a computed value attached to a field name that does not naturally exist on higher order value - the resolve __must__ be aware of the higher order value to pick from to compute its result.

**Comment by viniychuk** [comment]
well.. in your case `authorInitials` is basically the function of a each book's author... so technically your request should be more like this:
```
query {
  books {
    author {
        initials
    }
  }
}
```

Otherwise – your book is aware of initials and should have no problem resolving that field. Sorry if I'm missing the point – try to create a one-page schema file and just indicate there something like `//i want to be able to have X here`

**Comment by skyzyx** [comment]
@akomm: Can this issue be resolved?

**Comment by akomm** [comment]
yes
