### ISSUE TITLE
The right query

### ISSUE THREAD

**Issue by armetiz** [Youshido/GraphQL#198]
Hi there;

I'm dealing with dateTime formatted : 'Y-m-d H:i:s'
I define a custom DateTimeField to add format argument.

I can do something like that.

GraphQL query
```json
query {
  startAt
  startAtTime: startAt (format: "H:i:s")
}
```

But; do you know if this is possible to get the following

Expected JSON
```json
data: {
  startAt: {
    time: "12:30:00"
  }
}
```

Thanks a lot.
Regards.

**Comment by armetiz** [comment]
I think it related to this issue : https://github.com/graphql/graphql-js/issues/297

**Comment by skyzyx** [comment]
I've implemented something like this for my API. But the input query would need to be formatted like this (in order to get the expected JSON you posted).

```graphql
query {
  startAt {
    time(format: "H:i:s")
  }
}
```

```json
{
  "data": {
    "startAt": {
      "time": "12:30:00"
    }
  }
}
```

For the query you posted, you will only ever get something which looks like this:

```graphql
query {
  startAt
  startAtTime: startAt (format: "H:i:s")
}
```

```json
{
  "data": {
    "startAt": "2018-01-31T12:30:00Z",
    "startAtTime": "12:30:00"
  }
}
```

… or whatever your default time format for `startAt` is. Mine is [RFC 3339](https://tools.ietf.org/html/rfc3339).

A fundamental principle of GraphQL is that the input query and the output result should match in terms of overall tree structure.

**Comment by armetiz** [comment]
Hi @skyzyx an thanks for your answer.

> A fundamental principle of GraphQL is that the input query and the output result should match in terms of overall tree structure.

Yes, that what I've found on the Internet.

It's the same problem with firstName, lastName & name. Name is a dedicated field on the same level as firstName.
It could be address: String & addressComponents: AddressComponents { streetName }

Or startAtComponent { time, date }.

The problem is on Schema definition; not a technical GraphQL problem.

Regards.
Thomas.
